
version: 2

models:
    - name: HUB_COUNTRY
      description: "HUB table for Country"
      columns:
          - name: Country_Sk
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: Country_Bk
            description: "The business key for this table"
            tests:
                - not_null
          - name: Record_Source
            description: "Source of the record"
          - name: Load_Id
            description: "ID of the ELT Process when record was first time loaded"

    - name: HUB_USER
      description: "HUB table for the User"
      columns:
          - name: User_Sk
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: Username_Bk
            description: "The business key for this table"
            tests:
                - not_null                
          - name: Record_Source
            description: "Source of the record"
          - name: Load_Id
            description: "ID of the ELT Process when record was first time loaded"

    - name: LNK_USER_COUNTRY
      description: "LINK table between User and Country"
      columns:
          - name: User_Country_Sk
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: User_Sk
            description: "The HUB_User key"
            tests:
                - unique
                - not_null
          - name: Country_Sk
            description: "The HUB_Country key"
            tests:
                - unique
                - not_null

          - name: Username_Bk
            description: "The User business key"
            tests:
                - not_null      
          - name: Country_Bk
            description: "The Country business key"
            tests:
                - not_null                 
          - name: Record_Source
            description: "Source of the record"
          - name: Load_Id
            description: "ID of the ELT Process when record was first time loaded"      


snapshots:
  - name: SAT_COUNTRY
    description: "SAT for the Country"
    columns:
      - name: Country_Sk
        description: "The HUB_Country key, not unique for this table"
      - name: Country   
        description: "Country name"
      
  - name: SAT_USER
    description: "SAT for the User"
    columns:
      - name: User_Sk
        description: "The HUB_User key, not unique for this table"
      - name: First_Name
        description: "First name of the User, Attention: PII Data!"
      - name: Last_Name
        description: "Last name of the user, Attention: PII Data!"
      - name: Email
        description: "User's email, Attention: PII Data!"
      - name: Password
        description: "User's password, Attention: PII Data!"     
